name: Deno Tests

on:
  workflow_call:
    inputs:
      deno-version:
        description: Deno version
        type: string
        default: v2.x
      test-cmd:
        description: Shell command to run unit tests
        type: string
        default: deno task test
      working-directory:
        description: Working directory
        type: string
        default: "."
      runs-on:
        description: Runner
        type: string
        default: ubuntu-latest
      install-cmd:
        description: Command to install dependencies
        type: string
        default: deno install
      lint-cmd:
        description: Command to run lint
        type: string
        default: deno lint
      format-cmd:
        description: Command to run format
        type: string
        default: deno fmt --check
      e2e-test-cmd:
        description: Command to run end-to-end tests
        type: string
        default: ""
      e2e-install-cmd:
        description: Command to install end-to-end dependencies
        type: string
        default: ""
      e2e-continue-on-error:
        description: Allow E2E tests to fail without failing the CI
        type: boolean
        default: false

jobs:
  unit:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ${{ inputs.runs-on }}
    if: inputs.test-cmd != ''

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Install dependencies
        run: ${{ inputs.install-cmd }}

      - name: Run unit tests
        id: unit-tests
        run: ${{ inputs.test-cmd }}

  end-to-end:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ${{ inputs.runs-on }}
    if: inputs.e2e-test-cmd != ''

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Install dependencies
        run: |
          ${{ inputs.install-cmd }}
          ${{ inputs.e2e-install-cmd }}

      - name: Run end-to-end tests
        id: e2e-tests
        run: ${{ inputs.e2e-test-cmd }}
        continue-on-error: ${{ inputs.e2e-continue-on-error }}
