name: Link Check

on:
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        # docs at https://git.io/JBaKu
        with:
          config-file: .github/workflows/link-check-config.json
