name: NodeJS Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: NodeJS version
        type: string
        default: "24"
      install-cmd:
        description: Command to install dependencies
        type: string
        default: npm install
      e2e-install-cmd:
        description: |
          Extra install command for end-to-end tests, e.g. `npx playwright install chromium`.
          Empty by default to skip the browser download when not needed.
        type: string
        default: ""
      test-cmd:
        description: Shell command to run unit tests
        type: string
        default: npm run test
      e2e-test-cmd:
        description: Shell command to run E2E/integration tests. Leave empty to skip E2E tests. Usually something like `playwright test tests/*.ts`
        type: string
        default: ""
      working-directory:
        description: Working directory
        type: string
        default: "."
      runs-on:
        description: Runner label
        type: string
        default: ubuntu-latest

permissions:
  contents: read

jobs:
  unit:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ${{ inputs.runs-on }}
    if: inputs.test-cmd != ''

    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Set up node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}
          cache-dependency-path: ${{ inputs.working-directory }}/package.json

      - name: Install dependencies
        run: ${{ inputs.install-cmd }}

      - name: Run unit tests
        run: ${{ inputs.test-cmd }}

  end-to-end:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ${{ inputs.runs-on }}
    if: inputs.e2e-test-cmd != ''

    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Set up node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}
          cache-dependency-path: ${{ inputs.working-directory }}/package.json

      - name: Install dependencies
        run: |
          ${{ inputs.install-cmd }}
          ${{ inputs.e2e-install-cmd }}

      - name: Run end-to-end tests
        run: ${{ inputs.e2e-test-cmd }}
