name: Publish to NPM

on:
  workflow_call:
    inputs:
      node-version:
        description: NodeJS version
        type: number
        default: 22

jobs:
  tests:
    uses: ./.github/workflows/npm-test.yml

  release:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'release' && !github.event.pull_request.head.repo.fork
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Build package and publish to NPM
        run: |
          npm install
          npm run package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
