name: NPM Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: NodeJS version
        type: number
        default: 22
      install-cmd:
        description: Install dependencies
        type: string
        default: npm install
      install-e2e:
        description: Install browser for end-to-end tests
        type: string
        default: npx playwright install chromium
      test-cmd:
        description: Shell command to run tests
        type: string
        default: npm run test
      working-directory:
        description: Working directory
        type: string
        default: "."
      runs-on:
        description: Runner
        type: string
        default: ubuntu-latest

jobs:
  tests:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache-dependency-path: ${{ inputs.working-directory }}/package.json

      - name: Install dependencies
        run: |
          ${{ inputs.install-cmd }}
          ${{ inputs.install-e2e }}

      - name: Run tests
        id: tests
        run: ${{ inputs.test-cmd }}
