name: Publish to PyPI

on:
  workflow_call:
    inputs:
      os:
        description: Operating system
        type: string
        default: ubuntu-latest
      python-version:
        description: Python version
        type: string
        default: "3.11"
      uv-version:
        description: uv version
        type: string
        default: latest

# Note: PyPI trusted publishing doesn't currently support reusable workflows.
# You need to set PYPI_TOKEN as a repository secret for this workflow.
# In your PyPI account, generate an API token and add it as a GitHub repository secret.

jobs:
  release:
    runs-on: ${{ inputs.os }}
    permissions:
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv-version }}
          python-version: ${{ inputs.python-version }}

      - name: Build and publish package to PyPI
        run: |
          uv build
          uv publish --username __token__ --token ${{ secrets.PYPI_TOKEN }}
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
