name: Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version
        type: string
        default: "3.9"
      os:
        description: Operating system
        type: string
        default: ubuntu-latest
      pre-install-cmd:
        description: Run before install
        type: string
        default: ""
      install-uv:
        description: Install uv
        type: string
        default: "pip install uv"
      install-cmd-uv:
        description: Install dependencies with uv
        type: string
        default: "uv pip install -e '.[test]'  --system"
      test-cmd:
        description: Run tests
        type: string
        default: pytest --durations 0 --cov .
      pre-test:
        description: Run before tests
        type: string
        default: ""
      pre-release:
        description: Run before release
        type: string
        default: ""
      twine-username:
        description: User or org name for PyPI
        type: string
        default: __token__

jobs:
  tests:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        shell: bash
        run: |
          ${{ inputs.pre-install-cmd }}
          ${{ inputs.install-cmd-uv }}

      - name: Run tests
        id: tests
        run: |
          ${{ inputs.pre-test }}
          ${{ inputs.test-cmd }}

  release:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'release' && needs.tests.result == 'success'
    permissions:
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build and upload dist
        run: |
          pip install build twine
          python -m build
          twine check dist/* --strict
          ${{ inputs.pre-release }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
